### ISSUE TITLE
Computer Science End of Year BBQ

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/class-times#2]
This is a checklist of all the COMP courses and their times. Check off sections
that have been advertised to.

## Mon Wed
- [ ] COMP 3804 A (Michiel Smid, 08:35 - 09:55 Steacie Building 103)
- [ ] COMP 1805 D (Saeed Odak, 10:05 - 11:25 University Centre 231)
- [ ] COMP 2402 B (Alexa Sharp, 10:05 - 11:25 ON LINE)
- [ ] COMP 2501 A (Oliver van Kaick, 10:05 - 11:25 Southam Hall 520)
- [ ] COMP 4000 A (Anil Somayaji, 11:35 - 12:55 ON LINE)
- [x] ❗COMP 2404 C (Christine Laurendeau, 13:05 - 14:25 Loeb Building C264)
- [x] COMP 3005 A (Mengchi Liu, 13:05 - 14:25 Southam Hall THB)
- [x] COMP 3008 A (Elizabeth Stobert, 13:05 - 14:25 Tory Building 360)
- [x] COMP 2404 A (Darryl Hill, 14:35 - 15:55 Richcraft Hall 2200)
- [ ] COMP 3000 A (Lianying Zhao, 14:35 - 15:55 Azrieli Theatre 102)
- [ ] COMP 3009 A (Doron Nussbaum, 14:35 - 15:55 Tory Building 446)
- [ ] COMP 4202 A (Jorg Sack, 14:35 - 15:55 ON LINE)
- [ ] COMP 2401 B (Mark Lanthier, 16:05 - 17:25 Loeb Building C264)
- [ ] ❗COMP 4108 B (David Barrera, 16:05 - 17:25 Southam Hall 520)
- [x] ❗COMP 4900 C (Junfeng Wen, 16:05 - 17:25 Tory Building 210)
- [ ] COMP 2406 A (LD Nel, 18:05 - 19:25 ON LINE)
## Tue
- [ ] COMP 4308 A (Houman Moteshareie, 19:35 - 20:55 Nicol Building 4038)
## Tue Thu
- [ ] ❗COMP 1406 C (David McKenney, 08:35 - 09:55 Loeb Building C264)
- [ ] COMP 1501 A (Connor Hillen, 08:35 - 09:55 ON LINE)
- [ ] COMP 2404 B (Christine Laurendeau, 08:35 - 09:55 Nicol Building 4010)
- [ ] COMP 3005 B (Mengchi Liu, 08:35 - 09:55 Minto Centre 2000)
- [ ] COMP 4107 B (Matthew Holden, 08:35 - 09:55 Southam Hall 416)
- [ ] COMP 4805 A (Brett Stevens, 08:35 - 09:55 University Centre 376)
- [x] ❗COMP 1805 A (Alina Shaikhet, 10:05 - 11:25 Nicol Building 4010)
- [ ] COMP 3004 A (Vojislav Radonjic, 10:05 - 11:25 Southam Hall KM-TH)
- [ ] COMP 3203 A (AbdelRahman Abdou, 10:05 - 11:25 Steacie Building 103)
- [ ] COMP 1005 B (Connor Hillen, 11:35 - 12:55 Health Science Building 1301)
- [x] ❗COMP 1006 B (Jason Hinek, 11:35 - 12:55 Nicol Building 4010)
- [x] ❗COMP 1405 B (Connor Hillen, 11:35 - 12:55 Health Science Building 1301)
- [x] COMP 2109 A (Paul Van Oorschot, 11:35 - 12:55 Mackenzie Building 3165)
- [ ] ❗COMP 2402 A (Alexa Sharp, 11:35 - 12:55 Azrieli Theatre 102)
- [ ] COMP 3804 B (Michiel Smid, 11:35 - 12:55 Steacie Building 103)
- [ ] COMP 4501 A (Oliver van Kaick, 11:35 - 12:55 Canal Building 2104)
- [ ] COMP 4900 B (David Mould, 11:35 - 12:55 Southam Hall 309)
- [ ] COMP 3109 A (Jason Hinek, 13:05 - 14:25 Loeb Building C264)
- [x] COMP 2401 A (Connor Hillen, 14:35 - 15:55 Loeb Building C264)
- [x] COMP 3004 B (Vojislav Radonjic, 14:35 - 15:55 Azrieli Theatre 102)
- [ ] COMP 4900 A (John Oommen, 14:35 - 15:55 Loeb Building B243)
- [x] COMP 1406 A (Jason Hinek, 16:05 - 17:25 Loeb Building C264)
- [ ] COMP 2804 A (Darryl Hill, 16:05 - 17:25 Southam Hall KM-TH)
- [x] COMP 3007 B (Robert Collier, 16:05 - 17:25 Azrieli Theatre 101)
- [ ] COMP 4102 A (Michael Genkin, 16:05 - 17:25 ON LINE)
- [ ] COMP 4806 A (Emmanuel Lorin de la Grandmaison, 16:05 - 17:25 Herzberg Laboratories 3393)
- [ ] COMP 2406 B (LD Nel, 18:05 - 19:25 ON LINE)
- [ ] COMP 3000 B (Lianying Zhao, 18:05 - 19:25 Southam Hall THB)
- [ ] COMP 4203 A (Ahmad Traboulsi, 18:05 - 19:25 ON LINE)
## Wed
- [ ] COMP 3002 A (Wilf Lalonde, 18:05 - 20:55 Southam Hall 502)
## Wed Fri
- [ ] COMP 1005 A (Robert Collier, 08:35 - 09:55 Azrieli Theatre 301)
- [ ] COMP 1405 A (Robert Collier, 08:35 - 09:55 Azrieli Theatre 301)
- [ ] COMP 1406 B (David McKenney, 08:35 - 09:55 Loeb Building C264)
- [ ] COMP 2804 B (Darryl Hill, 08:35 - 09:55 Southam Hall THB)
- [ ] COMP 1406 E (Farah Chanchary, 11:35 - 12:55 Loeb Building C264)
- [ ] COMP 1001 B (Leila Chinaei, 14:35 - 15:55 Azrieli Theatre 302)
- [ ] COMP 1406 D (David McKenney, 14:35 - 15:55 Loeb Building C164)
- [x] COMP 1805 B (Alina Shaikhet, 14:35 - 15:55 Southam Hall THB)
- [ ] COMP 2601 A (Anil Somayaji, 14:35 - 16:25 ON LINE)
- [ ] COMP 1805 C (Alina Shaikhet, 16:05 - 17:25 Southam Hall THB)
- [ ] ❗COMP 3007 A (Robert Collier, 16:05 - 17:25 Azrieli Theatre 101)
## Fri
- [ ] COMP 3308 A (Nour Nissan, 12:35 - 14:25 Mackenzie Building 3328)

**Comment by AngelOnFira** [comment]
Ryan will do COMP 1805 A and 1006 B

**Comment by JohnLu2004** [comment]
COMP 1406 C (David McKenney, 08:35 - 09:55 Loeb Building C264)
 COMP 1805 A (Alina Shaikhet, 10:05 - 11:25 Nicol Building 4010)
 COMP 2402 A (Alexa Sharp, 11:35 - 12:55 Azrieli Theatre 102)

**Comment by AngelOnFira** [comment]
Shirley will do 2404C, 4108B, and 4900C, and 1405B

**Comment by AngelOnFira** [comment]
Victor covered 3005 A, and will cover 3007 A on Wednesday
